import 'user_role.dart';

enum Permission {
  viewDashboard,
  viewCopilot,
  viewOrders,
  manageOrders,
  viewKitchen,
  manageKitchen,
  viewInventory,
  manageInventory,
  viewEmployees,
  manageEmployees,
  viewAttendance,
  viewCustomers,
  manageCustomers,
  viewReservations,
  manageReservations,
  viewAccounting,
  manageAccounting,
  viewExpenses,
  viewInvoices,
  viewPayments,
  viewProfit,
  viewReports,
  viewAnalytics,
  viewBranches,
  manageBranches,
  viewSuppliers,
  manageSuppliers,
  viewPurchases,
  managePurchases,
  viewWaste,
  manageWaste,
  viewStockCount,
  manageStockCount,
  viewTransfers,
  manageTransfers,
  viewExpiry,
  viewAlerts,
  viewNotifications,
  viewAiAssistant,
  viewTables,
  viewPos,
  manageRefunds,
  viewAuditLogs,
  viewTodaysTasks,
  viewSettings,
  manageSettings,
}

const Map<UserRole, Set<Permission>> rolePermissions = {
  UserRole.owner: {
    Permission.viewDashboard,
    Permission.viewCopilot,
    Permission.viewOrders, Permission.manageOrders,
    Permission.viewKitchen, Permission.manageKitchen,
    Permission.viewInventory, Permission.manageInventory,
    Permission.viewEmployees, Permission.manageEmployees,
    Permission.viewAttendance,
    Permission.viewCustomers, Permission.manageCustomers,
    Permission.viewReservations, Permission.manageReservations,
    Permission.viewAccounting, Permission.manageAccounting,
    Permission.viewExpenses, Permission.viewInvoices,
    Permission.viewPayments, Permission.viewProfit,
    Permission.viewReports, Permission.viewAnalytics,
    Permission.viewBranches, Permission.manageBranches,
    Permission.viewSuppliers, Permission.manageSuppliers,
    Permission.viewPurchases, Permission.managePurchases,
    Permission.viewWaste, Permission.manageWaste,
    Permission.viewStockCount, Permission.manageStockCount,
    Permission.viewTransfers, Permission.manageTransfers,
    Permission.viewExpiry,
    Permission.viewAlerts, Permission.viewNotifications,
    Permission.viewAiAssistant,
    Permission.viewTables, Permission.viewPos,
    Permission.manageRefunds,
    Permission.viewAuditLogs,
    Permission.viewTodaysTasks,
    Permission.viewSettings, Permission.manageSettings,
  },
  UserRole.generalManager: {
    Permission.viewDashboard,
    Permission.viewCopilot,
    Permission.viewOrders, Permission.manageOrders,
    Permission.viewInventory,
    Permission.viewEmployees, Permission.manageEmployees,
    Permission.viewAttendance,
    Permission.viewCustomers,
    Permission.viewReservations, Permission.manageReservations,
    Permission.viewReports,
    Permission.viewBranches,
    Permission.viewAlerts, Permission.viewNotifications,
    Permission.viewAiAssistant,
    Permission.viewTodaysTasks,
    Permission.viewSettings,
  },
  UserRole.branchManager: {
    Permission.viewDashboard,
    Permission.viewOrders, Permission.manageOrders,
    Permission.viewKitchen, Permission.manageKitchen,
    Permission.viewInventory, Permission.manageInventory,
    Permission.viewEmployees,
    Permission.viewAttendance,
    Permission.viewCustomers,
    Permission.viewReservations,
    Permission.viewReports,
    Permission.viewAlerts, Permission.viewNotifications,
    Permission.viewTodaysTasks,
    Permission.viewSettings,
  },
  UserRole.supervisor: {
    Permission.viewOrders,
    Permission.viewEmployees,
    Permission.viewAttendance,
    Permission.viewInventory,
    Permission.viewAlerts, Permission.viewNotifications,
    Permission.viewTodaysTasks,
    Permission.viewSettings,
  },
  UserRole.cashier: {
    Permission.viewPos,
    Permission.viewOrders, Permission.manageOrders,
    Permission.manageRefunds,
    Permission.viewCustomers,
    Permission.viewNotifications,
    Permission.viewSettings,
  },
  UserRole.kitchen: {
    Permission.viewKitchen, Permission.manageKitchen,
    Permission.viewOrders,
    Permission.viewInventory,
    Permission.viewAlerts,
    Permission.viewNotifications,
    Permission.viewSettings,
  },
  UserRole.waiter: {
    Permission.viewTables,
    Permission.viewOrders, Permission.manageOrders,
    Permission.viewReservations, Permission.manageReservations,
    Permission.viewCustomers,
    Permission.viewNotifications,
    Permission.viewSettings,
  },
  UserRole.inventoryManager: {
    Permission.viewInventory, Permission.manageInventory,
    Permission.viewSuppliers, Permission.manageSuppliers,
    Permission.viewPurchases, Permission.managePurchases,
    Permission.viewTransfers, Permission.manageTransfers,
    Permission.viewWaste, Permission.manageWaste,
    Permission.viewExpiry,
    Permission.viewStockCount, Permission.manageStockCount,
    Permission.viewAlerts, Permission.viewNotifications,
    Permission.viewSettings,
  },
  UserRole.accountant: {
    Permission.viewAccounting, Permission.manageAccounting,
    Permission.viewExpenses,
    Permission.viewInvoices,
    Permission.viewPayments,
    Permission.viewProfit,
    Permission.viewReports,
    Permission.viewNotifications,
    Permission.viewSettings,
  },
};

extension RolePermissions on UserRole {
  Set<Permission> get permissions => rolePermissions[this] ?? {};
  bool can(Permission p) => permissions.contains(p);
}
